Update google-cloudrun-docker.yml

diff --git a/.github/workflows/google-cloudrun-docker.yml b/.github/workflows/google-cloudrun-docker.yml
--- a/.github/workflows/google-cloudrun-docker.yml
+++ b/.github/workflows/google-cloudrun-docker.yml
@@ -83,7 +83,9 @@ jobs:
       - name: Create env file
         id: env-file
         run: |-
+          cat .env || echo "failed"
           echo "${{ secrets.ENV_FILE }}" > .env
+          cat .env || echo "failed after"
           
       - name: Check env file
         id: env-check
