Update google-cloudrun-docker.yml

diff --git a/.github/workflows/google-cloudrun-docker.yml b/.github/workflows/google-cloudrun-docker.yml
--- a/.github/workflows/google-cloudrun-docker.yml
+++ b/.github/workflows/google-cloudrun-docker.yml
@@ -84,7 +84,7 @@ jobs:
         id: env-file
         run: |-
           cat .env || echo "failed"
-          echo "${{ secrets.ENV_FILE }}" > ./.env
+          echo "${{ secrets.ENV_FILE }}" > ./.env || echo "creation failed"
           cat .env || echo "failed after"
           
       - name: Check env file
